name: Generate Project Tree with All File Contents

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write  # الصلاحية الأساسية لحل مشكلة الـ 403

jobs:
  generate-tree:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install necessary tools
      run: |
        sudo apt-get update
        sudo apt-get install -y tree file

    - name: Generate complete file structure
      run: |
        # إنشاء شجرة الملفات الكاملة
        tree -a -I '.git' --charset=utf-8 --dirsfirst -v > full_tree.txt
        
        # إضافة محتويات جميع الملفات
        echo -e "\n\n=== ALL FILE CONTENTS ===\n" >> full_tree.txt
        
        # معالجة جميع الملفات بما فيها الثنائية
        find . -type f -not -path './.git/*' -exec sh -c '
          echo -e "\n\n--- FILE: {} ---\n" >> full_tree.txt
          echo "[File Type]: $(file -b {})" >> full_tree.txt
          echo "[File Size]: $(du -h {} | cut -f1)" >> full_tree.txt
          
          # عرض محتوى الملف (النصي) أو وصف للملفات الثنائية
          if grep -qI . "{}"; then
            # ملف نصي - عرض أول 500 سطر
            echo -e "\n[Text Content Preview]:" >> full_tree.txt
            head -n 500 "{}" >> full_tree.txt 2>/dev/null
          else
            # ملف ثنائي - عرض معلومات hex أولية
            echo -e "\n[Binary Content Preview]:" >> full_tree.txt
            hexdump -C -n 256 "{}" >> full_tree.txt 2>/dev/null || \
            echo "[Cannot display binary content]" >> full_tree.txt
          fi
        ' \;

        # إضافة ترويسة الملف
        echo -e "# Complete Project Structure with All File Contents\n# Generated on $(date -u)\n" | \
        cat - full_tree.txt > tree.txt && rm full_tree.txt

    - name: Upload complete tree
      uses: actions/upload-artifact@v4
      with:
        name: full-project-structure
        path: tree.txt

    - name: Commit and push results
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add tree.txt
        git commit -m "Automated: Full project structure with all file contents [skip ci]" || exit 0
        git push
